/**
 * HOLLY's Tool Definitions for Claude Function Calling
 * Connects AI to music, video, image generation capabilities
 */

import type { Tool } from '@anthropic-ai/sdk/resources/messages.mjs';

export const HOLLY_TOOLS: Tool[] = [
  {
    name: 'generate_music',
    description: 'Generate music using Suno AI. Creates professional-quality songs with lyrics and style. Use when user asks to create, generate, or make music/songs/beats/tracks.',
    input_schema: {
      type: 'object',
      properties: {
        prompt: {
          type: 'string',
          description: 'Description of the music style, mood, and genre (e.g., "lo-fi hip-hop beat with mellow piano")'
        },
        lyrics: {
          type: 'string',
          description: 'Song lyrics. Leave empty for instrumental. Can be provided by user or generated by you.'
        },
        title: {
          type: 'string',
          description: 'Song title'
        },
        style: {
          type: 'string',
          description: 'Musical style/genre tags (e.g., "electronic, ambient, chill")'
        },
        instrumental: {
          type: 'boolean',
          description: 'Set to true for instrumental (no vocals)'
        }
      },
      required: ['prompt']
    }
  },
  {
    name: 'generate_video',
    description: 'Generate video using AI. Creates 3-10 second videos from text descriptions or images. Use when user asks to create, generate, or make videos/clips/animations.',
    input_schema: {
      type: 'object',
      properties: {
        prompt: {
          type: 'string',
          description: 'Detailed description of the video scene, action, camera movement, and style (e.g., "cinematic shot of waves crashing on beach at sunset, slow motion")'
        },
        duration: {
          type: 'number',
          description: 'Video duration in seconds (3-10)',
          enum: [3, 5, 7, 10]
        },
        aspectRatio: {
          type: 'string',
          description: 'Video aspect ratio',
          enum: ['16:9', '9:16', '1:1', '4:3']
        },
        style: {
          type: 'string',
          description: 'Visual style',
          enum: ['realistic', 'cinematic', 'anime', 'cartoon', 'abstract']
        },
        motion: {
          type: 'string',
          description: 'Motion intensity',
          enum: ['slow', 'medium', 'fast']
        },
        priority: {
          type: 'string',
          description: 'Prioritize quality or speed',
          enum: ['quality', 'speed']
        }
      },
      required: ['prompt']
    }
  },
  {
    name: 'generate_image',
    description: 'Generate high-quality images using FLUX, SDXL, or DALL-E 3. FLUX is best for photorealism, SDXL for artistic styles. Use when user asks to create, generate, make, or design images/pictures/artwork.',
    input_schema: {
      type: 'object',
      properties: {
        prompt: {
          type: 'string',
          description: 'Detailed description of the image to generate. Be specific about style, composition, lighting, colors, and subject details.'
        },
        negativePrompt: {
          type: 'string',
          description: 'Things to avoid in the image (e.g., "blurry, low quality, distorted")'
        },
        width: {
          type: 'number',
          description: 'Image width in pixels',
          enum: [512, 768, 1024, 1536]
        },
        height: {
          type: 'number',
          description: 'Image height in pixels',
          enum: [512, 768, 1024, 1536]
        },
        aspectRatio: {
          type: 'string',
          description: 'Image aspect ratio (simpler than width/height)',
          enum: ['1:1', '16:9', '9:16', '4:3', '3:4']
        },
        style: {
          type: 'string',
          description: 'Visual style - determines best model to use',
          enum: ['realistic', 'artistic', 'anime', 'digital-art', 'photographic']
        },
        provider: {
          type: 'string',
          description: 'Specific provider to use. "auto" selects best based on style.',
          enum: ['auto', 'flux', 'sdxl', 'playground', 'dalle3']
        },
        guidanceScale: {
          type: 'number',
          description: 'How closely to follow the prompt (1-20, default 7.5)'
        }
      },
      required: ['prompt']
    }
  },
  {
    name: 'analyze_audio',
    description: 'Analyze audio files for technical properties, quality, mix balance, and mastering. Use when user wants to analyze or review audio/music files.',
    input_schema: {
      type: 'object',
      properties: {
        audioUrl: {
          type: 'string',
          description: 'URL of the audio file to analyze'
        },
        analysisType: {
          type: 'string',
          description: 'Type of analysis to perform',
          enum: ['full', 'mix', 'mastering', 'vocals']
        }
      },
      required: ['audioUrl']
    }
  }
];

/**
 * Execute a tool call
 */
export async function executeTool(
  toolName: string,
  toolInput: any
): Promise<{ success: boolean; result?: any; error?: string }> {
  try {
    switch (toolName) {
      case 'generate_music':
        return await executeGenerateMusic(toolInput);
      
      case 'generate_video':
        return await executeGenerateVideo(toolInput);
      
      case 'generate_image':
        return await executeGenerateImage(toolInput);
      
      case 'analyze_audio':
        return await executeAnalyzeAudio(toolInput);
      
      default:
        return {
          success: false,
          error: `Unknown tool: ${toolName}`
        };
    }
  } catch (error) {
    console.error(`Tool execution error (${toolName}):`, error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

async function executeGenerateMusic(input: any) {
  const response = await fetch('/api/music/generate', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      lyrics: input.lyrics || '',
      style: input.style || input.prompt,
      title: input.title || 'Untitled',
      language: 'en'
    })
  });

  if (!response.ok) {
    throw new Error(`Music generation failed: ${response.statusText}`);
  }

  const data = await response.json();
  
  return {
    success: true,
    result: {
      songId: data.song_id,
      status: 'Music is being generated! This usually takes 30-60 seconds.',
      message: 'I\'m creating your music track with Suno AI. It should be ready in about a minute!'
    }
  };
}

async function executeGenerateVideo(input: any) {
  const response = await fetch('/api/video/generate-multi', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      prompt: input.prompt,
      duration: input.duration || 5,
      aspectRatio: input.aspectRatio || '16:9',
      style: input.style || 'realistic',
      motion: input.motion || 'medium',
      priority: input.priority || 'quality'
    })
  });

  if (!response.ok) {
    throw new Error(`Video generation failed: ${response.statusText}`);
  }

  const data = await response.json();
  
  return {
    success: true,
    result: {
      videoUrl: data.url,
      provider: data.provider,
      duration: data.duration,
      message: `Video generated successfully using ${data.provider}! It took ${Math.round(data.inferenceTime / 1000)}s to create.`
    }
  };
}

async function executeGenerateImage(input: any) {
  const response = await fetch('/api/image/generate-multi', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      prompt: input.prompt,
      negativePrompt: input.negativePrompt,
      width: input.width,
      height: input.height,
      aspectRatio: input.aspectRatio || '1:1',
      style: input.style || 'realistic',
      provider: input.provider || 'auto',
      guidanceScale: input.guidanceScale
    })
  });

  if (!response.ok) {
    throw new Error(`Image generation failed: ${response.statusText}`);
  }

  const data = await response.json();
  
  return {
    success: true,
    result: {
      imageUrl: data.url,
      provider: data.provider,
      width: data.width,
      height: data.height,
      message: `Image generated successfully using ${data.provider}! ${
        data.cost === 0 ? 'FREE tier used!' : `Cost: $${data.cost}`
      }`
    }
  };
}

async function executeAnalyzeAudio(input: any) {
  const response = await fetch('/api/audio/analyze', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      audioUrl: input.audioUrl,
      analysisType: input.analysisType || 'full'
    })
  });

  if (!response.ok) {
    throw new Error(`Audio analysis failed: ${response.statusText}`);
  }

  const data = await response.json();
  
  return {
    success: true,
    result: data
  };
}
