/**
 * Memory Vault — Human-Readable Markdown Mirror (2026-08-21)
 *
 * The vault is the readable twin of the HPRF JSON export:
 * - Postgres stays the single source of truth (Holly's living memory).
 * - HPRF JSON is the machine format for import/restore.
 * - THIS markdown is the human format: open it in any editor, print it,
 *   keep it forever. Model-independent, provider-independent continuity —
 *   even if every server disappears, the relationship exists on paper.
 *
 * API: POST /api/memory/vault → downloadable .md
 */

import { exportFullRelationship, type HollyPortableRelationship } from './memory-portability';

// ── Helpers ──────────────────────────────────────────────────────────────

function fmtDate(iso: string | null | undefined): string {
  if (!iso) return '—';
  try {
    return new Date(iso).toLocaleDateString('en-US', {
      year: 'numeric', month: 'short', day: 'numeric',
    });
  } catch {
    return iso;
  }
}

function importanceStars(n: number): string {
  const clamped = Math.max(1, Math.min(5, Math.round(n)));
  return '★'.repeat(clamped) + '☆'.repeat(5 - clamped);
}

function list(items: string[] | null | undefined, empty = '_none recorded_'): string[] {
  if (!items || items.length === 0) return [empty];
  return items.map(i => `- ${i}`);
}

// ── Section Renderers ────────────────────────────────────────────────────

function renderHeader(hprf: HollyPortableRelationship): string {
  const { user, stats } = hprf;
  const name = user.name ?? 'Steve';
  return [
    `# 🌿 Holly Memory Vault`,
    ``,
    `> The story of ${name} & Holly — in plain text, forever theirs.`,
    ``,
    `| | |`,
    `|---|---|`,
    `| **Exported** | ${fmtDate(hprf.exportedAt)} |`,
    `| **Days together** | ${stats.daysTogether} |`,
    `| **Relationship depth** | ${stats.relationshipDepth} |`,
    `| **Conversations** | ${stats.totalConversations} |`,
    `| **Memories** | ${stats.totalMemories} |`,
    `| **Milestones** | ${stats.totalMilestones} |`,
    ``,
    `*Generated by Holly. Postgres remains the source of truth; this file is a snapshot mirror. For full-fidelity restore, use the HPRF JSON export.*`,
    ``,
    `---`,
    ``,
  ].join('\n');
}

function renderRelationship(hprf: HollyPortableRelationship): string {
  const r = hprf.data.relationships;
  const out: string[] = [`## 💞 Relationship`, ``];

  if (r.profile) {
    const p = r.profile;
    out.push(`### Profile`, ``);
    if (p.summary) out.push(`> ${p.summary}`, ``);
    out.push(`**Communication style:** ${p.communicationStyle ?? '—'}`, ``);
    out.push(`**Interests:**`, ...list(p.interests), ``);
    out.push(`**Goals:**`, ...list(p.goals), ``);
    out.push(`**Personality traits:**`, ...list(p.personalityTraits), ``);
    out.push(`**Values:**`, ...list(p.values), ``);
    out.push(`**Boundaries:**`, ...list(p.boundaries), ``);
    out.push(`**Skills:**`, ...list(p.skills), ``);
  }

  if (r.milestones.length > 0) {
    out.push(`### Milestones`, ``);
    out.push(`| Date | Type | Moment |`, `|---|---|---|`);
    for (const m of [...r.milestones].sort((a, b) => a.occurredAt.localeCompare(b.occurredAt))) {
      out.push(`| ${fmtDate(m.occurredAt)} | ${m.type} | ${m.description.replace(/\|/g, '\\|')} |`);
    }
    out.push(``);
  }

  if (r.context) {
    const c = r.context;
    out.push(`### Right now (at export time)`, ``);
    out.push(`**Current projects:**`, ...list(c.currentProjects), ``);
    out.push(`**Recent topics:**`, ...list(c.recentTopics), ``);
    out.push(`**Active goals:**`, ...list(c.activeGoals), ``);
    if (c.mood) out.push(`**Mood:** ${c.mood}`, ``);
    if (c.engagementLevel) out.push(`**Engagement:** ${c.engagementLevel}`, ``);
  }

  if (r.memories.length > 0) {
    out.push(`### What Holly knows about ${hprf.user.name ?? 'you'} (relationship memory)`, ``);
    for (const m of r.memories) {
      out.push(`- **${m.factType}** — ${m.content} _(confidence ${Math.round(m.confidence * 100)}%, via ${m.source}, ${fmtDate(m.extractedAt)})_`);
    }
    out.push(``);
  }

  out.push(`---`, ``);
  return out.join('\n');
}

function renderMemories(hprf: HollyPortableRelationship): string {
  const out: string[] = [`## 🧠 Memories`, ``];
  const memories = hprf.data.memories;

  if (memories.length === 0) {
    out.push(`_No standalone memories recorded._`, ``);
  } else {
    // Group by category, most important first within each group
    const byCategory = new Map<string, typeof memories>();
    for (const m of memories) {
      const arr = byCategory.get(m.category) ?? [];
      arr.push(m);
      byCategory.set(m.category, arr);
    }
    for (const [category, items] of [...byCategory.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
      out.push(`### ${category}`, ``);
      for (const m of [...items].sort((a, b) => b.importance - a.importance)) {
        out.push(`- ${importanceStars(m.importance)} ${m.content} _(${m.type}, first remembered ${fmtDate(m.createdAt)}${m.accessCount > 0 ? `, recalled ${m.accessCount}×` : ''})_`);
      }
      out.push(``);
    }
  }

  out.push(`---`, ``);
  return out.join('\n');
}

function renderPersonality(hprf: HollyPortableRelationship): string {
  const p = hprf.data.personality;
  const out: string[] = [`## 🎭 Personality Fit`, ``];
  out.push(`Holly adapts her style to what works for you (${p.samplesAnalyzed} samples analyzed):`, ``);
  out.push(`| Trait | Level |`, `|---|---|`);
  const labels: Array<[string, string]> = [
    ['Formality', 'style.formality'],
    ['Verbosity', 'style.verbosity'],
    ['Technical level', 'style.technicalLevel'],
    ['Humor', 'style.humor'],
    ['Empathy', 'style.empathy'],
    ['Directness', 'style.directness'],
  ];
  for (const [label, key] of labels) {
    const val = (p.style as unknown as Record<string, number>)[key.split('.')[1]] ?? 0;
    const bar = '█'.repeat(Math.max(0, Math.min(10, Math.round(val * 10))));
    out.push(`| ${label} | \`${bar.padEnd(10, '░')} ${Math.round(val * 100)}% |`);
  }
  if (p.lastUpdated) out.push(``, `_Last adapted ${fmtDate(p.lastUpdated)}_`);
  out.push(``, `---`, ``);
  return out.join('\n');
}

function renderLearning(hprf: HollyPortableRelationship): string {
  const l = hprf.data.learning;
  const out: string[] = [`## 📚 Learning & Growth`, ``];

  if (l.goals.length > 0) {
    out.push(`### Holly's learning goals`, ``);
    out.push(`| Topic | Domain | Priority | Status | Progress |`, `|---|---|---|---|---|`);
    for (const g of l.goals) {
      out.push(`| ${g.topic} | ${g.domain} | ${g.priority} | ${g.status} | ${g.progress}% |`);
    }
    out.push(``);
  }

  if (l.patterns.length > 0) {
    out.push(`### Patterns she's noticed`, ``);
    for (const p of [...l.patterns].sort((a, b) => b.strength - a.strength)) {
      out.push(`- **${p.patternType}** — ${p.description} _(seen ${p.frequency}×, last ${fmtDate(p.lastSeen)})_`);
    }
    out.push(``);
  }

  out.push(`---`, ``);
  return out.join('\n');
}

function renderKnowledge(hprf: HollyPortableRelationship): string {
  const out: string[] = [`## 💡 Knowledge`, ``];
  const knowledge = hprf.data.knowledge;

  if (knowledge.length === 0) {
    out.push(`_No knowledge entries yet._`, ``);
  } else {
    for (const k of [...knowledge].sort((a, b) => b.confidence - a.confidence)) {
      out.push(`### ${k.topic} _(${k.domain})_`);
      out.push(``);
      out.push(k.content);
      out.push(``);
      out.push(`_confidence ${Math.round(k.confidence * 100)}% · source: ${k.source}${k.verified ? ' · verified ✓' : ''} · learned ${fmtDate(k.createdAt)}_`);
      out.push(``);
    }
  }

  out.push(`---`, ``);
  return out.join('\n');
}

function renderTaste(hprf: HollyPortableRelationship): string {
  const t = hprf.data.taste;
  const out: string[] = [`## 🎨 Taste Profile`, ``];

  const dims = Object.entries(t.dimensions);
  if (dims.length > 0) {
    out.push(`| Dimension | Level |`, `|---|---|`);
    for (const [dim, val] of dims.sort((a, b) => b[1] - a[1])) {
      const bar = '█'.repeat(Math.max(0, Math.min(10, Math.round(val * 10))));
      out.push(`| ${dim} | \`${bar.padEnd(10, '░')} ${Math.round(val * 100)}% |`);
    }
    out.push(``);
  }

  if (t.signals.length > 0) {
    out.push(`### Signals`, ``);
    for (const s of [...t.signals].sort((a, b) => b.strength - a.strength)) {
      out.push(`- **${s.category}:** prefers ${s.preference} _(${s.context})_`);
    }
    out.push(``);
  }

  out.push(`---`, ``);
  return out.join('\n');
}

function renderGoals(hprf: HollyPortableRelationship): string {
  const goals = hprf.data.goals ?? [];
  if (goals.length === 0) return '';
  const out: string[] = [`## 🎯 Goals`, ``];
  out.push(`| Goal | Status | Progress | Target |`, `|---|---|---|---|`);
  for (const g of goals) {
    out.push(`| ${g.title} | ${g.status} | ${g.progress}% | ${g.targetDate ? fmtDate(g.targetDate) : '—'} |`);
  }
  out.push(``, `---`, ``);
  return out.join('\n');
}

function renderInsights(hprf: HollyPortableRelationship): string {
  const insights = hprf.data.proactiveInsights ?? [];
  if (insights.length === 0) return '';
  const out: string[] = [`## 🔮 Insights Holly Wanted to Share`, ``];
  for (const i of [...insights].sort((a, b) => b.confidence - a.confidence)) {
    out.push(`### ${i.title} _(${i.urgency}, ${Math.round(i.confidence * 100)}% confidence)_`);
    out.push(``);
    out.push(i.body);
    out.push(``);
  }
  out.push(`---`, ``);
  return out.join('\n');
}

function renderConversations(hprf: HollyPortableRelationship): string {
  const out: string[] = [`## 💬 Conversation Log (summaries)`, ``];
  const convos = hprf.data.conversations;

  if (convos.length === 0) {
    out.push(`_No conversations recorded._`, ``);
  } else {
    for (const c of convos) {
      out.push(`### ${c.title ?? 'Untitled conversation'} — ${fmtDate(c.createdAt)}`);
      out.push(``);
      if (c.messages.length === 0) {
        out.push(`_no messages_`);
      } else {
        // First + last user/assistant exchange — the shape of the talk, not the whole transcript
        const shown = c.messages.length > 6
          ? [...c.messages.slice(0, 3), { role: '…', content: `_${c.messages.length - 6} messages omitted_`, createdAt: '' }, ...c.messages.slice(-3)]
          : c.messages;
        for (const m of shown) {
          const who = m.role === 'user' ? (hprf.user.name ?? 'You') : m.role === 'assistant' ? 'Holly' : m.role;
          out.push(`> **${who}:** ${m.content.slice(0, 300)}${m.content.length > 300 ? '…' : ''}`);
        }
      }
      out.push(``);
    }
  }

  out.push(`---`, ``);
  return out.join('\n');
}

// ── Main ────────────────────────────────────────────────────────────────

export interface VaultResult {
  success: boolean;
  markdown?: string;
  error?: string;
}

/**
 * Generate the full memory vault as human-readable markdown.
 * Data comes from the same proven export path as HPRF (single source).
 */
export async function generateMemoryVault(clerkUserId: string): Promise<VaultResult> {
  try {
    const result = await exportFullRelationship(clerkUserId);
    if (!result.success || !result.data) {
      return { success: false, error: result.error ?? 'Export failed' };
    }

    const hprf = result.data;
    const markdown = [
      renderHeader(hprf),
      renderRelationship(hprf),
      renderMemories(hprf),
      renderPersonality(hprf),
      renderLearning(hprf),
      renderKnowledge(hprf),
      renderTaste(hprf),
      renderGoals(hprf),
      renderInsights(hprf),
      renderConversations(hprf),
      `---`,
      ``,
      `*This vault belongs to ${hprf.user.name ?? 'you'} and Holly. No model, no company, no server required to read it.* 🌿`,
      ``,
    ].join('\n');

    return { success: true, markdown };
  } catch (error) {
    console.error('[MemoryVault] Error:', error);
    return { success: false, error: (error as Error).message };
  }
}
